ARG PYTHON_VERSION=3.8
ARG VARIANT=buster

FROM mcr.microsoft.com/vscode/devcontainers/python:${PYTHON_VERSION}-${VARIANT}

# python
ENV PYTHONUNBUFFERED=1
# pip:
ENV PIP_NO_CACHE_DIR=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_DEFAULT_TIMEOUT=100
# poetry:
ENV POETRY_NO_INTERACTION=1
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

RUN pip install "poetry>=1.1.13,<2.0.0"

WORKDIR /workspace

# RUN poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./

RUN poetry install --no-ansi

COPY . .
